<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <!-- AWS SDK for Lambda and S3/Step Functions -->
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.9.1" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.9.4" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.1" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.18" />
    <PackageReference Include="AWSSDK.StepFunctions" Version="4.0.2.9" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.3.19" />
    <PackageReference Include="HtmlSanitizer" Version="9.0.892" />
    
    <!-- MongoDB for local development -->
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
    
    <!-- JWT handling -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer " Version="10.0.2" />
    
    <!-- Configuration and dependency injection -->
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    
    <!-- Logging -->
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.2" />
    
    <!-- Utilities -->
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
  </ItemGroup>

</Project>
