#!/bin/bash
# Reads Cognito config from LocalStack and writes implementation/spa/.env.local.
# Run this after docker-compose up to configure the SPA for local development.
#
# Usage:  ./scripts/generate-spa-env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${REPO_ROOT}/localstack-data/cognito-config.env"
ENV_FILE="${REPO_ROOT}/implementation/spa/.env.local"

echo "=== Generating SPA environment for local development ==="

if [ -f "$CONFIG_FILE" ]; then
  echo "Reading config from localstack-data/cognito-config.env..."
  # shellcheck source=/dev/null
  . "$CONFIG_FILE"
  COGNITO_DOMAIN="${COGNITO_DOMAIN}"
else
  echo "Config file not found — querying LocalStack directly..."
  echo "(Make sure docker-compose is running and LocalStack has finished initialising.)"

  export AWS_ACCESS_KEY_ID=test
  export AWS_SECRET_ACCESS_KEY=test
  AWS_OPTS="--endpoint-url=http://localhost:4566 --region=us-east-1 --no-cli-pager"

  USER_POOL_ID=$(aws $AWS_OPTS cognito-idp list-user-pools --max-results 60 \
    --query 'UserPools[?Name==`zero-trust-local`].Id | [0]' --output text)

  if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" = "None" ]; then
    echo "ERROR: Cognito User Pool not found."
    echo "       Ensure LocalStack is running:  docker-compose up -d"
    echo "       Then wait ~30s for it to initialise and try again."
    exit 1
  fi

  CLIENT_ID=$(aws $AWS_OPTS cognito-idp list-user-pool-clients \
    --user-pool-id "$USER_POOL_ID" \
    --query 'UserPoolClients[?ClientName==`zero-trust-spa`].ClientId | [0]' --output text)

  COGNITO_DOMAIN="zero-trust-local.auth.us-east-1.localhost.localstack.cloud:4566"
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/generate-spa-env.sh — do not commit.
# Re-run this script after docker-compose up to refresh values.
VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_APP_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
VITE_COGNITO_REDIRECT_SIGN_IN=http://localhost:5173/callback
VITE_COGNITO_REDIRECT_SIGN_OUT=http://localhost:5173
VITE_API_BASE_URL=http://localhost:5000
EOF

echo ""
echo "Written to implementation/spa/.env.local"
echo "  User Pool ID  : ${USER_POOL_ID}"
echo "  Client ID     : ${CLIENT_ID}"
echo "  Cognito URL   : https://${COGNITO_DOMAIN}/login"
echo ""
echo "Start the SPA:"
echo "  cd implementation/spa && npm run dev"
